Comment instead of fail for files check in infra-check (#infra)
The infra-check workflow shouldn't fail when you are changing files which are
not infra specific files. In plenty of situations we need to change Makefile
which is shipped but it's pretty safe to be changed.

So instead of fail just comment on the PR that you should do a double check for
these files.

diff --git a/.github/workflows/infra-check.yml b/.github/workflows/infra-check.yml
--- a/.github/workflows/infra-check.yml
+++ b/.github/workflows/infra-check.yml
@@ -6,6 +6,7 @@ on:
 
 permissions:
   contents: read
+  pull-requests: write
 
 jobs:
   infra-check:
@@ -42,6 +43,7 @@ jobs:
 
       - name: Check if all changed files are infra related
         run: |
+          set -eu
           changed_files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}..HEAD)
           # print for debugging
           echo "----- Changed files -----"
@@ -52,6 +54,7 @@ jobs:
           . .structure-config
 
           failed_check="no"
+          echo -e 'Infrastructure check **failed** on these files. Please do a double check of these files before merge!\n' > ./message.txt
 
           for f in $changed_files; do
             matched="no"
@@ -64,12 +67,14 @@ jobs:
             done
 
             if [ $matched == "no" ]; then
-              echo "$f is not part of the infrastructure"
+              echo "$f" | tee -a ./message.txt
               failed_check="yes"
             fi
 
           done
 
           if [ "$failed_check" == "yes" ]; then
-            exit 1
+            gh pr comment ${{ github.event.pull_request.number }} -F ./message.txt
           fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
