Move the infra-check files check as last check (#infra)
I want to avoid failing the whole check based on this. This has more an
informative character that you should do double review.

Because of that it give sense to have that as the last part of the workflow so
the workflow could strong checks solve first and fail on that.

diff --git a/.github/workflows/infra-check.yml b/.github/workflows/infra-check.yml
--- a/.github/workflows/infra-check.yml
+++ b/.github/workflows/infra-check.yml
@@ -29,6 +29,17 @@ jobs:
           git log --oneline -1 origin/${{ github.event.pull_request.base.ref }}
           git rebase origin/${{ github.event.pull_request.base.ref }}
 
+      - name: Check if all commits have (#infra)
+        run: |
+          # match (#infra) at the end of the commit message
+          for i in "$(git log --oneline origin/${{ github.event.pull_request.base.ref }}..HEAD)"; do
+
+            if ! [[ $i =~ \(#infra\)$ ]]; then
+              echo "$i --> Is missing (#infra!)"
+              exit 1
+            fi
+          done
+
       - name: Check if all changed files are infra related
         run: |
           changed_files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}..HEAD)
@@ -62,14 +73,3 @@ jobs:
           if [ "$failed_check" == "yes" ]; then
             exit 1
           fi
-
-      - name: Check if all commits have (#infra)
-        run: |
-          # match (#infra) at the end of the commit message
-          for i in "$(git log --oneline origin/${{ github.event.pull_request.base.ref }}..HEAD)"; do
-
-            if ! [[ $i =~ \(#infra\)$ ]]; then
-              echo "$i --> Is missing (#infra!)"
-              exit 1
-            fi
-          done
